import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import './globals.css';
import ThemeProviderPage from './theme-provider';

const poppins = Poppins({ subsets: ['latin'], weight: '500' });

export const metadata: Metadata = {
  title: process.env.customKey,
  description: 'Generated by Tiago Persch',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <ThemeProviderPage>
          {children}
          <ToastContainer />
        </ThemeProviderPage>
      </body>
    </html>
  );
}
