import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Suspense } from "react";

import "./globals.css";
import Loading from "./loading";
import ThemeProviderPage from "./theme-provider";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: process.env.customKey,
  description: "Generated by Tiago Persch",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <ThemeProviderPage>
        <Suspense fallback={<Loading />}>
          <body className={poppins.className}>
            <main className="flex flex-col">{children}</main>
          </body>
        </Suspense>
      </ThemeProviderPage>
    </html>
  );
}
